version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          command: |
            echo "Empty workflow for ci purpose"

workflows:
  build-all:
    jobs:
      - build