version: 2

defaults: &defaults
  working_directory: ~/qlik-word-cloud
  docker:
    - image: circleci/node:stretch
  environment:
    GITHUB_ORG: "qlik-oss"
    GITHUB_REPO: "br.com.clever.wordcloud"
    PACKAGE_NAME: "qlik-word-cloud"

jobs:
  test:
    docker:
      - image: circleci/node:stretch-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: BlackDuck scan
          command: curl -s https://detect.synopsys.com/detect.sh | bash -s -- \
            --blackduck.url="https://qliktech.blackducksoftware.com" \
            --blackduck.trust.cert=true \
            --blackduck.username="svc-blackduck" \
            --blackduck.password=${svc_blackduck} \
            --detect.project.name="viz-bundle-qlik-word-cloud"
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-word-cloud
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build and package
          command: |
            yarn build
            yarn sense
          environment:
            NODE_ENV: production
      - persist_to_workspace:
          root: ~/qlik-word-cloud
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist

workflows:
  version: 2
  master_flow:
    jobs:
      - test
      - build:
          requires:
            - test
