version: 2

defaults: &defaults
  working_directory: ~/qlik-word-cloud
  docker:
    - image: cimg/node:lts-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-word-cloud
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: Build and package
          command: |
            pnpm build
            pnpm sense
          environment:
            NODE_ENV: production
      - run:
          name: Install Playwright
          command: |
            npx playwright install
      - run:
          name: Rendering tests
          command: pnpm test:rendering
      - store_artifacts:
          path: test/rendering/index.spec.js-snapshots
      - store_artifacts:
          path: ./test/rendering/__artifacts__
      - store_artifacts:
          path: test/rendering/test-report
      - persist_to_workspace:
          root: ~/qlik-word-cloud
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist

workflows:
  version: 2
  master_flow:
    jobs:
      - build
