name: Build
on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        required: true
        default: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: qlik-oss/sn-gh-workflows/.github/workflows/build.yaml@main
    secrets: inherit
    with:
      release: ${{ inputs.release || false}}
